apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest
  labels:
    app: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: loadtest
        image: teacr.azurecr.io/loadtest:latest
        env:
        - name: JAVA_OPTS
          value: "-XX:+UseG1GC -XX:MaxRAMPercentage=70"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          timeoutSeconds: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - loadtest
            topologyKey: "kubernetes.io/hostname"
