apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: springboot
        image: teacr.azurecr.io/springboot:latest
        env:
        - name: JAVA_OPTS
          value: ""
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          timeoutSeconds: 1
