apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sampleapp-parallelgc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: internal-sampleapp-parallelgc
            port:
              number: 80
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sampleapp-g1gc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: internal-sampleapp-g1gc
            port:
              number: 80
  ingressClassName: nginx
